import { Module, Lesson, Exercise } from './types';

export const MODULES: Module[] = [
  {
    id: 'water-confidence',
    level: 'beginner-1',
    title: 'Water Confidence & Safety',
    description: 'Build comfort and safety awareness in water',
    duration: '2-4 weeks',
    prerequisites: [],
    lessons: [
      {
        id: 'getting-comfortable',
        moduleId: 'water-confidence',
        title: 'Getting Comfortable in Water',
        description: 'Learn to relax and move confidently in shallow water',
        duration: '15 min',
        difficulty: 'beginner',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
        thumbnailUrl: 'https://images.unsplash.com/photo-1530549387789-4c1017266635?w=800',
        skills: ['Water entry', 'Walking in water', 'Basic movements'],
        prerequisites: [],
        steps: [],
        drills: [],
        commonMistakes: [],
        checklistItems: [
          'I can enter the water confidently',
          'I can walk comfortably in chest-deep water',
          'I can perform basic movements without fear',
        ],
      },
      {
        id: 'breathing-fundamentals',
        moduleId: 'water-confidence',
        title: 'Breathing Fundamentals',
        description: 'Master rhythmic breathing techniques',
        duration: '15 min',
        difficulty: 'beginner',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
        thumbnailUrl: 'https://images.unsplash.com/photo-1519315901367-f34ff9154487?w=800',
        skills: ['Inhale technique', 'Exhale underwater', 'Breath control'],
        prerequisites: ['getting-comfortable'],
        steps: [],
        drills: [],
        commonMistakes: [],
        checklistItems: [
          'I can exhale comfortably underwater',
          'I can inhale quickly above water',
          'I can maintain rhythmic breathing',
        ],
      },
      {
        id: 'floating-front',
        moduleId: 'water-confidence',
        title: 'Floating on Front',
        description: 'Learn to float face-down with confidence',
        duration: '15 min',
        difficulty: 'beginner',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
        thumbnailUrl: 'https://images.unsplash.com/photo-1560089000-7433a4ebbd64?w=800',
        skills: ['Front float position', 'Relaxation', 'Recovery to standing'],
        prerequisites: ['breathing-fundamentals'],
        steps: [],
        drills: [],
        commonMistakes: [],
        checklistItems: [
          'I can float on my front for 30 seconds',
          'I can remain relaxed while floating',
          'I can recover to standing safely',
        ],
      },
      {
        id: 'floating-back',
        moduleId: 'water-confidence',
        title: 'Floating on Back',
        description: 'Master the essential survival skill of back floating',
        duration: '15 min',
        difficulty: 'beginner',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
        thumbnailUrl: 'https://images.unsplash.com/photo-1576610616656-d3aa5d1f4534?w=800',
        skills: ['Back float position', 'Breathing while floating', 'Recovery technique'],
        prerequisites: ['floating-front'],
        steps: [],
        drills: [],
        commonMistakes: [],
        checklistItems: [
          'I can assume back float position without assistance',
          'I can maintain horizontal body position for 30+ seconds',
          'I can breathe comfortably while floating',
          'I can recover to standing position safely',
        ],
      },
    ],
  },
  {
    id: 'foundation-skills',
    level: 'beginner-2',
    title: 'Foundation Skills',
    description: 'Build fundamental swimming techniques',
    duration: '4-6 weeks',
    prerequisites: ['water-confidence'],
    lessons: [
      {
        id: 'body-position',
        moduleId: 'foundation-skills',
        title: 'Body Position & Streamline',
        description: 'Learn proper horizontal body alignment',
        duration: '20 min',
        difficulty: 'beginner',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
        thumbnailUrl: 'https://images.unsplash.com/photo-1438029071396-1e831a7fa6d8?w=800',
        skills: ['Streamline position', 'Body alignment', 'Core engagement'],
        prerequisites: ['floating-back'],
        steps: [],
        drills: [],
        commonMistakes: [],
        checklistItems: [
          'I can maintain horizontal body position',
          'I understand streamline form',
          'I can engage my core while swimming',
        ],
      },
    ],
  },
];

export const DRYLAND_EXERCISES: Exercise[] = [
  {
    id: 'freestyle-arm-circles',
    title: 'Freestyle Arm Circles',
    category: 'simulation',
    difficulty: 'beginner',
    equipment: [],
    targetedMuscles: ['Shoulders', 'Upper back', 'Core'],
    duration: '2-3 min',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800',
    steps: [
      {
        number: 1,
        title: 'Setup',
        description: 'Stand with feet shoulder-width apart. Engage your core. Arms relaxed at sides.',
        imageUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400',
      },
      {
        number: 2,
        title: 'Movement',
        description: 'Extend right arm forward and up, mimicking freestyle stroke. Rotate torso as arm moves (simulate breathing rotation). Complete full circle, brushing thumb past thigh. Repeat with left arm. Continue alternating for 30 seconds.',
        imageUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400',
        breathing: 'Exhale as arm pulls back, inhale as arm reaches forward',
        reps: '20 per arm OR 1 minute continuous',
      },
    ],
    formTips: [
      'Keep core tight throughout movement',
      'Full range of motion - fingertips should touch above head',
      'Maintain smooth, controlled rotations',
      'Focus on mimicking your swimming motion',
    ],
    commonMistakes: [
      "Don't shrug shoulders up - keep them relaxed",
      'Avoid stiff, robotic movements - stay fluid',
      "Don't rush - quality over speed",
      'Keep your core engaged throughout',
    ],
    modifications: {
      easier: 'Slow down tempo, focus on form',
      harder: 'Add resistance band, increase speed, hold light weights',
      injury: 'If shoulder pain, reduce range of motion',
    },
    swimmingConnection: 'Strengthens the exact muscle groups used in freestyle stroke. Builds muscle memory for proper arm path and rotation. Improves shoulder endurance for longer swimming sessions.',
  },
  {
    id: 'plank-shoulder-taps',
    title: 'Plank with Shoulder Taps',
    category: 'strength',
    difficulty: 'intermediate',
    equipment: [],
    targetedMuscles: ['Core', 'Shoulders', 'Arms'],
    duration: '3 min',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800',
    steps: [
      {
        number: 1,
        title: 'Starting Position',
        description: 'Begin in high plank position with hands directly under shoulders. Body should form a straight line from head to heels.',
        imageUrl: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400',
        breathing: 'Breathe steadily throughout',
      },
      {
        number: 2,
        title: 'Shoulder Taps',
        description: 'Keep hips stable. Tap right hand to left shoulder, return to plank. Then tap left hand to right shoulder. Minimize hip rotation.',
        imageUrl: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400',
        reps: '20 total taps (10 each side)',
      },
    ],
    formTips: [
      'Keep hips square - minimal rotation',
      'Maintain straight line from head to heels',
      'Engage your core to prevent sagging',
      'Move with control, not speed',
    ],
    commonMistakes: [
      "Don't let hips rock side to side",
      'Avoid sagging hips or raised bottom',
      "Don't hold your breath - breathe consistently",
      'Keep neck neutral - look at the floor',
    ],
    modifications: {
      easier: 'Perform from knees instead of toes',
      harder: 'Add push-up between taps, increase reps',
      injury: 'Skip if wrist pain present',
    },
    swimmingConnection: 'Builds core stability essential for maintaining horizontal body position in water. Strengthens shoulders for endurance swimming.',
  },
  {
    id: 'flutter-kicks',
    title: 'Dryland Flutter Kicks',
    category: 'simulation',
    difficulty: 'beginner',
    equipment: [],
    targetedMuscles: ['Hip flexors', 'Quads', 'Core'],
    duration: '2 min',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=800',
    steps: [
      {
        number: 1,
        title: 'Position',
        description: 'Lie on back with hands placed under hips for lower back support. Keep lower back pressed to floor. Lift legs slightly off ground.',
        imageUrl: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=400',
      },
      {
        number: 2,
        title: 'Kicking',
        description: 'Keep legs relatively straight (slight knee bend). Alternate quick, small kicks. Kick from the hips, not the knees. Pointed toes.',
        imageUrl: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=400',
        breathing: 'Breathe steadily throughout',
        reps: '30 seconds, rest, repeat 3 times',
      },
    ],
    formTips: [
      'Keep kicks small and fast - 6 inches amplitude',
      'Point your toes like a ballerina',
      'Kick from the hip, keep knees mostly straight',
      'Press lower back into floor',
    ],
    commonMistakes: [
      "Don't bend knees too much - keep legs extended",
      'Avoid large, slow kicks - keep them quick and compact',
      "Don't arch your lower back off the floor",
      'Keep toes pointed, not flexed',
    ],
    modifications: {
      easier: 'Reduce kick speed and duration, bend knees slightly more',
      harder: 'Lift head and shoulders off ground, increase duration',
      injury: 'Stop if lower back pain occurs. Keep legs higher if needed.',
    },
    swimmingConnection: 'Mimics the exact freestyle and backstroke kick pattern. Builds leg endurance and hip flexor strength for sustained kicking in the pool.',
  },
];

export const ASSESSMENT_QUESTIONS = {
  waterComfort: {
    question: 'How comfortable are you in water?',
    options: [
      { value: 'very-uncomfortable', emoji: '😰', label: 'Very Uncomfortable', description: "I'm afraid of water/have had traumatic experience" },
      { value: 'uncomfortable', emoji: '😟', label: 'Uncomfortable', description: "I'm nervous in water deeper than waist-high" },
      { value: 'neutral', emoji: '😐', label: 'Neutral', description: "I'm okay in shallow water but anxious in deep end" },
      { value: 'comfortable', emoji: '🙂', label: 'Comfortable', description: "I can relax in deep water but can't swim well" },
      { value: 'very-comfortable', emoji: '😄', label: 'Very Comfortable', description: "I'm confident in deep water" },
    ],
  },
  swimmingAbility: {
    question: 'Which best describes your swimming ability?',
    options: [
      { value: 'non-swimmer', emoji: '🚫', label: 'Non-swimmer', description: 'I cannot swim at all' },
      { value: 'beginner', emoji: '🌊', label: 'Beginner', description: 'I can float/doggy paddle but no proper strokes' },
      { value: 'basic-swimmer', emoji: '🏊♀️', label: 'Basic Swimmer', description: 'I can do basic freestyle but tire quickly' },
      { value: 'intermediate', emoji: '🏊', label: 'Intermediate', description: 'I can swim multiple strokes with some technique' },
      { value: 'advanced', emoji: '🏊♂️', label: 'Advanced', description: 'I swim regularly with good form' },
    ],
  },
  fitnessLevel: {
    question: 'How would you rate your current fitness level?',
    options: [
      { value: 'sedentary', emoji: '🛋️', label: 'Sedentary', description: 'Little to no regular exercise' },
      { value: 'lightly-active', emoji: '🚶', label: 'Lightly Active', description: 'Walk/light exercise 1-2x per week' },
      { value: 'moderately-active', emoji: '🏃', label: 'Moderately Active', description: 'Exercise 3-4x per week' },
      { value: 'very-active', emoji: '💪', label: 'Very Active', description: 'Exercise 5+ times per week' },
      { value: 'athlete', emoji: '🏋️', label: 'Athlete', description: 'Regular intense training' },
    ],
  },
};
